name: "CI Multiplatform Build"

on: [push, pull_request]

jobs:
  ubuntu_1804:
    name: "Ubuntu 18.04"
    runs-on: [ubuntu-18.04]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.3
      - name: "Install dependencies"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./CI/linux/install-dependencies-ubuntu.sh
      - name: "Build Plugin"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./CI/linux/build-ubuntu.sh``
      - name: "Package Plugin"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          ./CI/linux/package.sh
          ./CI/linux/package-ubuntu.sh
  ubuntu_2004:
    name: "Ubuntu 20.04"
    runs-on: [ubuntu-20.04]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.3
      - name: "Install dependencies"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./CI/linux/install-dependencies-ubuntu.sh
      - name: "Build Plugin"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: ./CI/linux/build-ubuntu.sh``
      - name: "Package Plugin"
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          ./CI/linux/package.sh
          ./CI/linux/package-ubuntu.sh
